---
# tasks file for ansible-vagrant
- name: Create custome box directory
  file:
    name: "/home/{{ item }}/vagrant/boxes"
    state: directory
    mode: 0755
  with_items:
    - "{{ vagrant_users }}"
  when: vagrant_users

- name: APT - Install Vagrant on Debian
  apt:
    deb: "{{ debian_download_url }}" 
    state: present
  when: ansible_os_family == "Debian"

- name: YUM - Install Vagrant on RHEL
  yum:
    name: "{{ rhel_download_url }}"
    state: present
  when: ansible_os_family == "RedHat"

- include: "vagrant-libvirt-apt-dependancies.yml"
  when: ansible_os_family == "Debian" and install_vagrant_libvirt

- include: "vagrant-libvirt-yum-dependancies.yml"
  when: ansible_os_family == "RedHat" and install_vagrant_libvirt

- include: "libvirt-networks.yml"
  when: install_vagrant_libvirt

- include: "plugins.yml"
  when: vagrant_plugins


