---
- name: YUM - Install Dependancies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "qemu"
    - "libvirt"
    - "libvirt-devel"
    - "ruby-devel"
    - "gcc"
    - "qemu-kvm"
